### PR TITLE
Replace usages of EntityId.fromString with constructors

### PR DESCRIPTION
**Pull request by bdmogal**

### CODE REVIEW

**Comment by poornachandra** [comment]
LGTM, thanks for fixing this.

**Comment by bdmogal** [comment]
http://builds.cask.co/browse/TRAC-BT23

**Comment by bdmogal** [comment]
Success. Merging.

**Comment by anwar6953** [comment]
`EntityId.fromString` implementation changed?

**Comment by bdmogal** [comment]
Yes, it expects ``version`` now. In any case, ``fromString`` shouldn't be used to create an ``EntityId`` outside of CDAP (where you have individual components). We should probably remove that method into a CDAP-internal class.

**Pull request merged**
